### ISSUE TITLE
Uploading

### ISSUE THREAD

**Issue by krisdavis** [krisdavis/GIFtoolsCookbook#2]
So BitBucket has a place I can upload binary files (such as images) so people can download them and not have them in version control. Where is that feature???

**Comment by lheagy** [comment]
I have never tried to do this, but think there might be a workaround. If you wanted to store the images on a server somewhere, you could point to those without having them directly in the repo. 

Other than that, I think that using readthedocs to build and host the documentation will be easiest if the images are just included in the repo under version control.

**Comment by krisdavis** [comment]
OK, I'll add the images to the repository and not worry about it for now. If they get too big, then I'll deal with it. I was thinking about having them on the gifraid2, but I don't think people would necessarily have that capability to link if working from home, etc.
