### ISSUE TITLE
Tried to create branch...

### ISSUE THREAD

**Issue by sdevriese** [krisdavis/GIFtoolsCookbook#3]
I created a branch named "sarah"
Then made some changes
Committed those changes
But I can't push them (don't have the privilege from my own branch?)
Nor does the branch show up on github website (or show a little branching off thing in sourcetree in a different colour)
:/

**Comment by lheagy** [comment]
@krisdavis needs to give you permission to push to the repo.

**Comment by krisdavis** [comment]
Done; you have access.
